### ISSUE TITLE
可以提供一下表结构吗？谢谢

### ISSUE THREAD

**Issue by Kun-37** [LeYunone/codex#1]
希望可以将表结构初始化文件加到项目中，谢谢~

**Comment by LeYunone** [comment]
非常抱歉因为一些事情现在才能回，可以看最新的README，以及项目的演示地址[http://leyunone.com:7878/codex/#/](http://leyunone.com:7878/codex/#/) 🤝

**Comment by Kun-37** [comment]
感谢~~
